theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "System"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"



[[block]]
block = "cpu"
interval = 1
format = "{utilization}% {frequency}GHz"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}° avg"
chip = "*-isa-*"

[[block]]
block = "net"
device = "wlp0s20u1"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} updates available"
format_singular = "{pacman} update available"
format_up_to_date = "no update"
critical_updates_regex = "(linux |linux-lts|linux-zen)"

[[block]]
block = "weather"
format = "{location} {weather} {temp}°C {humidity}%"
service = { name = "openweathermap", api_key = "6abd401820c40711563a8678414fe71d", city_id = "1816670", units = "metric" }

[[block]]
block = "time"
interval = 60
format = " %m/%d/%y %R"